[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cocktail-etl"
version = "0.1.0"
description = "ETL project for extracting cocktail recipes from Difford's Guide."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "httpx",
    "beautifulsoup4",
    "psycopg[binary]",
]
[tool.setuptools.packages.find]
include = ["app*"]
exclude = ["data*", "tests*"]

[project.optional-dependencies]
dev = [
    "pytest",
]
